/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package dashboardContents;

import java.awt.Frame;

/**
 *
 * @author Iredafe
 */
public class MyDashboard extends javax.swing.JFrame {

    /**
     * Creates new form MyDashboard
     */
    public MyDashboard() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        button2 = new java.awt.Button();
        button3 = new java.awt.Button();
        button4 = new java.awt.Button();
        button8 = new java.awt.Button();
        button6 = new java.awt.Button();
        txtResult = new javax.swing.JTextField();
        cob = new javax.swing.JCheckBox();
        cp = new javax.swing.JCheckBox();
        c_fat = new javax.swing.JCheckBox();
        la = new javax.swing.JCheckBox();
        cold = new javax.swing.JCheckBox();
        fever = new javax.swing.JCheckBox();
        wl = new javax.swing.JCheckBox();
        cl3w = new javax.swing.JCheckBox();
        ns = new javax.swing.JCheckBox();
        cpob = new javax.swing.JCheckBox();
        btnDiagnose = new java.awt.Button();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        h_ache = new javax.swing.JCheckBox();
        vom = new javax.swing.JCheckBox();
        diar = new javax.swing.JCheckBox();
        rash = new javax.swing.JCheckBox();
        s_pain = new javax.swing.JCheckBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 204, 0));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setText("PATIENT DIAGNOSTIC SYSTEM");

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setText("X");
        jLabel4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel4MouseClicked(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel5.setText("_");
        jLabel5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel5MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(279, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(154, 154, 154)
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel4)
                .addGap(19, 19, 19))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(25, 25, 25))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 860, -1));

        jPanel2.setBackground(new java.awt.Color(255, 204, 0));

        button2.setBackground(new java.awt.Color(0, 0, 204));
        button2.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        button2.setForeground(new java.awt.Color(255, 255, 255));
        button2.setLabel("TREATMENT");

        button3.setBackground(new java.awt.Color(0, 0, 204));
        button3.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        button3.setForeground(new java.awt.Color(255, 255, 255));
        button3.setLabel("ADVICE");

        button4.setBackground(new java.awt.Color(0, 0, 204));
        button4.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        button4.setForeground(new java.awt.Color(255, 255, 255));
        button4.setLabel("SAVE");

        button8.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        button8.setForeground(new java.awt.Color(0, 0, 204));
        button8.setLabel("PRINT");

        button6.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        button6.setForeground(new java.awt.Color(0, 51, 204));
        button6.setLabel("CLEAR");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(61, 61, 61)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(button4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(button3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(button2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(button8, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(button6, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(73, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(button2, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(22, 22, 22)
                .addComponent(button3, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(19, 19, 19)
                .addComponent(button4, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(121, 121, 121)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(button8, javax.swing.GroupLayout.DEFAULT_SIZE, 36, Short.MAX_VALUE)
                    .addComponent(button6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(74, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 60, 270, -1));

        txtResult.setBackground(new java.awt.Color(204, 204, 204));
        getContentPane().add(txtResult, new org.netbeans.lib.awtextra.AbsoluteConstraints(23, 386, 465, 81));

        cob.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        cob.setText("Coughing up Blood");
        getContentPane().add(cob, new org.netbeans.lib.awtextra.AbsoluteConstraints(25, 151, -1, -1));

        cp.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        cp.setText("Chest Pains");
        getContentPane().add(cp, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 190, -1, -1));

        c_fat.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        c_fat.setText("Constant Fatigue");
        getContentPane().add(c_fat, new org.netbeans.lib.awtextra.AbsoluteConstraints(165, 151, -1, -1));

        la.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        la.setText("Loss of Appetite");
        getContentPane().add(la, new org.netbeans.lib.awtextra.AbsoluteConstraints(165, 192, -1, -1));

        cold.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        cold.setText("Cold");
        cold.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                coldActionPerformed(evt);
            }
        });
        getContentPane().add(cold, new org.netbeans.lib.awtextra.AbsoluteConstraints(438, 151, -1, -1));

        fever.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        fever.setText("Fever");
        getContentPane().add(fever, new org.netbeans.lib.awtextra.AbsoluteConstraints(438, 230, -1, -1));

        wl.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        wl.setText("Weight Loss");
        getContentPane().add(wl, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 230, -1, -1));

        cl3w.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        cl3w.setText("Coughing that Lasts for 3 or more Weeks");
        getContentPane().add(cl3w, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 270, -1, -1));

        ns.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        ns.setText("Night Sweat");
        getContentPane().add(ns, new org.netbeans.lib.awtextra.AbsoluteConstraints(438, 192, -1, -1));

        cpob.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        cpob.setText("Chest Pains when Breathing or Coughing");
        getContentPane().add(cpob, new org.netbeans.lib.awtextra.AbsoluteConstraints(165, 230, -1, -1));

        btnDiagnose.setBackground(new java.awt.Color(0, 0, 255));
        btnDiagnose.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        btnDiagnose.setForeground(new java.awt.Color(255, 255, 255));
        btnDiagnose.setLabel("DIAGNOSE");
        btnDiagnose.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnDiagnoseMouseClicked(evt);
            }
        });
        getContentPane().add(btnDiagnose, new org.netbeans.lib.awtextra.AbsoluteConstraints(23, 349, -1, -1));

        jLabel2.setFont(new java.awt.Font("Microsoft JhengHei UI", 1, 12)); // NOI18N
        jLabel2.setText("Please tick the Appropriate Boxes that describe your condition below.");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 130, 440, -1));

        jLabel3.setFont(new java.awt.Font("Segoe Print", 3, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 255));
        jLabel3.setText("Diagnosis for Tuberculosis, Malaria and Typhoid");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 80, 320, 30));

        h_ache.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        h_ache.setText("Headaches");
        getContentPane().add(h_ache, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 270, -1, -1));

        vom.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        vom.setText("Vomiting");
        getContentPane().add(vom, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 270, -1, -1));

        diar.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        diar.setText("Diarrhea");
        getContentPane().add(diar, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 310, -1, -1));

        rash.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        rash.setText("Rash");
        getContentPane().add(rash, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 310, -1, -1));

        s_pain.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        s_pain.setText("Stomach pains");
        getContentPane().add(s_pain, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 310, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void coldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_coldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_coldActionPerformed

    private void btnDiagnoseMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnDiagnoseMouseClicked
if ((cob.isSelected())&& (cl3w.isSelected())&&(cpob.isSelected())) {
    txtResult.setText("Tuberculosis Suspected");
}else{ txtResult.setText("Tuberculosis not Suspected");


if((fever.isSelected())&& (h_ache.isSelected()) && (vom.isSelected()) && 
        (ns.isSelected()) && cold.isSelected()) 
     {txtResult.setText("Malaria Suspected");
     }else{txtResult.setText("Malaria not Suspected");
             
             }
if ((fever.isSelected()) && (la.isSelected()) && (rash.isSelected()) && 
        (diar.isSelected()) && (s_pain.isSelected()))
{txtResult.setText("Typhoid Fever Suspected");
}else{txtResult.setText("Typhoid Fever not Suspected");

}
// TODO add your handling code here:
    }//GEN-LAST:event_btnDiagnoseMouseClicked
    }
    private void jLabel4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel4MouseClicked
System.exit(0);
        
// TODO add your handling code here:
    }//GEN-LAST:event_jLabel4MouseClicked

    private void jLabel5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel5MouseClicked
this.setState(Frame.ICONIFIED);
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel5MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MyDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MyDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MyDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MyDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MyDashboard().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private java.awt.Button btnDiagnose;
    private java.awt.Button button2;
    private java.awt.Button button3;
    private java.awt.Button button4;
    private java.awt.Button button6;
    private java.awt.Button button8;
    private javax.swing.JCheckBox c_fat;
    private javax.swing.JCheckBox cl3w;
    private javax.swing.JCheckBox cob;
    private javax.swing.JCheckBox cold;
    private javax.swing.JCheckBox cp;
    private javax.swing.JCheckBox cpob;
    private javax.swing.JCheckBox diar;
    private javax.swing.JCheckBox fever;
    private javax.swing.JCheckBox h_ache;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JCheckBox la;
    private javax.swing.JCheckBox ns;
    private javax.swing.JCheckBox rash;
    private javax.swing.JCheckBox s_pain;
    private javax.swing.JTextField txtResult;
    private javax.swing.JCheckBox vom;
    private javax.swing.JCheckBox wl;
    // End of variables declaration//GEN-END:variables
}
